Repository airbytehq/connector-builder-mcp, pull requests merged in 2025-09, with the labels that each got.

#60 feat: add more robust config parsing (str as json)
  connector_builder_mcp/_secrets.py
  connector_builder_mcp/_util.py
  connector_builder_mcp/validation_testing.py
Labels: enhancement

#62 feat: Add check-gh-actions poe task for actionlint CLI
  poe_tasks.toml
Labels: enhancement

#64 feat: add manager-developer agent architecture with handoffs
  .github/workflows/build-connector-command.yml
  .github/workflows/build-connector-test.yml
  connector_builder_agents/prompts/phase-1-stream-read.md
  connector_builder_agents/prompts/phase-2-pagination.md
  connector_builder_agents/prompts/phase-3-remaining-streams.md
  connector_builder_agents/prompts/root-prompt-headless.md
  connector_builder_agents/prompts/root-prompt.md
  connector_builder_agents/pyproject.toml
  connector_builder_agents/src/__init__.py
  connector_builder_agents/src/_util.py
  connector_builder_agents/src/agents.py
  connector_builder_agents/src/cli.py
  connector_builder_agents/src/constants.py
  connector_builder_agents/src/guidance.py
  connector_builder_agents/src/phases.py
  connector_builder_agents/src/run.py
  connector_builder_agents/src/tools.py
  connector_builder_agents/uv.lock
  connector_builder_mcp/connector_builder.py
  examples/mcp_agent.config.yaml
  examples/run_mcp_agent.py
  poe_tasks.toml
  pyproject.toml
Labels: enhancement

#75 docs: Update README with addlt. MCP server configurations
  README.md
Labels: docs

#88 feat: add reporting tools and misc fix bugs
  connector_builder_agents/pyproject.toml
  connector_builder_agents/src/agents.py
  connector_builder_agents/src/guidance.py
  connector_builder_agents/src/run.py
  connector_builder_agents/src/tools.py
  connector_builder_agents/uv.lock
  connector_builder_mcp/validation_testing.py
  poe_tasks.toml
  pyproject.toml
  uv.lock
Labels: enhancement

#90 feat: add proper secrets handling and ci-based execution workflows
  .github/workflows/build-connector-command.yml
  .github/workflows/build-connector-test.yml
  connector_build_tests/connector-matrix.prompts.yaml
  connector_builder_agents/evals/README.md
  connector_builder_agents/src/_util.py
  connector_builder_agents/src/cli.py
  connector_builder_agents/src/run.py
  connector_builder_agents/src/tools.py
  connector_builder_mcp/connector_builder.py
  connector_builder_mcp/manifest_scaffold.py
  connector_builder_mcp/secrets.py
  connector_builder_mcp/validation_testing.py
  tests/integration/test_privatebin.py
  tests/unit/test_secrets.py
Labels: enhancement

#95 feat: explicit locally scoped secrets directory
  .github/workflows/build-connector-command.yml
  .github/workflows/build-connector-test.yml
  .gitignore
  connector_builder_agents/src/_util.py
Labels: enhancement

#94 fix: update static-args to treat PR number as optional in slash command dispatch
  .github/workflows/slash-command-dispatch.yml
Labels: bug, security

#98 docs: split evals runbook into working and non-working sections
  connector_builder_agents/evals/README.md
Labels: docs

#96 fix: use `.secrets` dir within `cwd` (not parent)
  .github/workflows/deptry-dependency-analysis.yml
  connector_builder_agents/src/_util.py
Labels: bug, security

#92 chore: refactor to remove global state
  connector_builder_agents/src/agents.py
  connector_builder_agents/src/constants.py
  connector_builder_agents/src/run.py
  connector_builder_agents/src/tools.py
Labels: chore

#91 feat: add evals using arize phoenix
  connector_builder_agents/pyproject.toml
  connector_builder_agents/src/evals/__init__.py
  connector_builder_agents/src/evals/data/connectors.yaml
  connector_builder_agents/src/evals/dataset.py
  connector_builder_agents/src/evals/evaluators.py
  connector_builder_agents/src/evals/helpers.py
  connector_builder_agents/src/evals/phoenix_run.py
  connector_builder_agents/src/evals/task.py
  connector_builder_agents/src/run.py
  connector_builder_agents/uv.lock
  poe_tasks.toml
  uv.lock
Labels: enhancement
